kind: pipeline
type: docker
name: container-test-and-build

steps:

# for unit testing
- name: tests
  image: golang
  environment:
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: noobee
    DB_PASS: noobee
    DB_NAME: noobee
  depends_on:
    - db
  commands:
  - make run-test

# for build image docker
- name : build
  image: plugins/docker
  settings: 
    repo: achimonchi/drone-test
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest
    dockerfile: Multistage-Alpine-Dockerfile
  when:
    event:
    - tag
    - push
  depends_on:
    - tests

services:
- name: db
  image: postgres
  environment:
    POSTGRES_PASSWORD: noobee
    POSTGRES_USER: noobee
    POSTGRES_DB: noobee

trigger:
  branch:
  - main
  event:
  - push
  - tag

---
kind: pipeline
type: docker
name: deploy

steps:
- name: deploy to server
  image: appleboy/drone-ssh
  settings:
    host:
      - ssh_server
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - docker run -d --name go-drone-tests --network=host  \
        -e DB_HOST=localhost \
        -e DB_PORT=5432 \
        -e DB_USER=postgres \
        -e DB_PASS=admin \
        -e DB_NAME=noobeeid \
        achimonchi/drone-test
depends_on:
- container-test-and-build