kind: pipeline
type: docker
name: default

steps:

# for unit testing
- name: tests
  image: golang
  environment:
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: noobee
    DB_PASS: noobee
    DB_NAME: noobee
  depends_on:
    - db
  commands:
  - make run-test

# for build image docker
- name : build
  image: plugins/docker
  settings: 
    repo: achimonchi/drone-test
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    dockerfile: Multistage-Alpine-Dockerfile
  when:
    event:
    - tag
  depends_on:
    - tests

services:
- name: db
  image: postgres
  environment:
    POSTGRES_PASSWORD: noobee
    POSTGRES_USER: noobee
    POSTGRES_DB: noobee

trigger:
  branch:
  - main
  event:
  - push
  - tag