kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.19
  commands:
    - make run-test
  # when:
  #    event:
  #    - push

trigger:
  branch:
  - main
  event:
  - push