kind: pipeline
type: docker
name: default

steps:

- name: tests
  image: golang
  environment:
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: noobee
    DB_PASS: noobee
    DB_NAME: noobee
  depends_on:
    - db
  commands:
  - sh test.sh

services:
- name: db
  image: postgres
  environment:
    POSTGRES_PASSWORD: noobee
    POSTGRES_USER: noobee
    POSTGRES_DB: noobee

trigger:
  branch:
  - main
  event:
  - push